CC = javac

all: Freeway FreewayF FreewayG FreewayApp

Freeway: Freeway.java
	$(CC) Freeway.java

FreewayF: FreewayF.java
	$(CC) FreewayF.java

FreewayG: FreewayG.java
	$(CC) FreewayG.java

FreewayApp: FreewayApp.java
	$(CC) FreewayApp.java

